include(${ProjDirPath}/flags_common.cmake)

SET(__CMAKE_C_FLAGS_RAM " \
    ${CMAKE_C_FLAGS_BASE} \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING=1 \
")

SET(__CMAKE_C_FLAGS_FLEXSPI_NOR_SDRAM " \
    ${CMAKE_C_FLAGS_BASE} \
    -DXIP_EXTERNAL_FLASH=1 \
    -DXIP_BOOT_HEADER_ENABLE=1 \
    -DXIP_BOOT_HEADER_DCD_ENABLE=0 \
    -DXIP_BOOT_HEADER_XMCD_ENABLE=1 \
    -DUSE_SDRAM \
")

SET(CMAKE_ASM_FLAGS_DEBUG " ${CMAKE_ASM_FLAGS_BASE} -DDEBUG ")
SET(CMAKE_ASM_FLAGS_RELEASE " ${CMAKE_ASM_FLAGS_BASE} -DNDEBUG ")
SET(CMAKE_ASM_FLAGS_FLEXSPI_NOR_SDRAM_DEBUG " ${CMAKE_ASM_FLAGS_BASE} -DDEBUG -D__STARTUP_INITIALIZE_RAMFUNCTION ")

# TODO - optimize for release
SET(CMAKE_C_FLAGS_DEBUG " ${__CMAKE_C_FLAGS_RAM} -DDEBUG -g -O0 -DDATA_SECTION_IS_CACHEABLE=0 ")
SET(CMAKE_C_FLAGS_RELEASE " ${__CMAKE_C_FLAGS_RAM} -DNDEBUG -O0 -DDATA_SECTION_IS_CACHEABLE=1")
SET(CMAKE_C_FLAGS_FLEXSPI_NOR_SDRAM_DEBUG " ${__CMAKE_C_FLAGS_FLEXSPI_NOR_SDRAM} -DDEBUG -g -O0 -DDATA_SECTION_IS_CACHEABLE=0 ")

SET(CMAKE_CXX_FLAGS_DEBUG " ${CMAKE_CXX_FLAGS_BASE} -DDEBUG -g -O0 -DDATA_SECTION_IS_CACHEABLE=0 ")
SET(CMAKE_CXX_FLAGS_RELEASE " ${CMAKE_CXX_FLAGS_BASE} -DNDEBUG -O0 -DDATA_SECTION_IS_CACHEABLE=1 ")
SET(CMAKE_CXX_FLAGS_FLEXSPI_NOR_SDRAM_DEBUG " ${CMAKE_CXX_FLAGS_BASE} -DDEBUG -g -O0 -DDATA_SECTION_IS_CACHEABLE=0 ")

SET(CMAKE_EXE_LINKER_FLAGS_DEBUG " \
    ${CMAKE_EXE_LINKER_FLAGS_BASE} \
    -g \
    -T\"${ProjDirPath}/MIMXRT1176xxxxx_cm7_ram.ld\" -static \
")

SET(CMAKE_EXE_LINKER_FLAGS_RELEASE " \
    ${CMAKE_EXE_LINKER_FLAGS_BASE} \
    -g \
    -T\"${ProjDirPath}/MIMXRT1176xxxxx_cm7_ram.ld\" -static \
")

SET(CMAKE_EXE_LINKER_FLAGS_FLEXSPI_NOR_SDRAM_DEBUG " \
    ${CMAKE_EXE_LINKER_FLAGS_BASE} \
    -Xlinker --defsym=__stack_size__=2048 \
    -Xlinker --defsym=__heap_size__=25600 \
    -g \
    -T\"${ProjDirPath}/MIMXRT1176xxxxx_cm7_flexspi_nor_sdram.ld\" -static \
")
